// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"encoding/json"
	"time"
)

type OrgMember struct {
	OrgID    string
	UserID   string
	Role     string
	JoinedAt time.Time
}

type Organization struct {
	ID        string
	Name      string
	Slug      string
	Personal  bool
	OwnerID   string
	Settings  json.RawMessage
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Team struct {
	ID          string
	OrgID       string
	Name        string
	Description *string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type TeamMember struct {
	TeamID   string
	UserID   string
	JoinedAt time.Time
}
