// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/jackc/pgx/v5/pgconn"
)

const addOrgMember = `-- name: AddOrgMember :exec

INSERT INTO org_members (org_id, user_id, role, joined_at)
VALUES ($1, $2, $3, $4)
`

type AddOrgMemberParams struct {
	OrgID    string
	UserID   string
	Role     string
	JoinedAt time.Time
}

// Org member queries
func (q *Queries) AddOrgMember(ctx context.Context, arg AddOrgMemberParams) error {
	_, err := q.db.Exec(ctx, addOrgMember,
		arg.OrgID,
		arg.UserID,
		arg.Role,
		arg.JoinedAt,
	)
	return err
}

const addTeamMember = `-- name: AddTeamMember :exec
INSERT INTO team_members (team_id, user_id, joined_at)
VALUES ($1, $2, $3)
`

type AddTeamMemberParams struct {
	TeamID   string
	UserID   string
	JoinedAt time.Time
}

func (q *Queries) AddTeamMember(ctx context.Context, arg AddTeamMemberParams) error {
	_, err := q.db.Exec(ctx, addTeamMember, arg.TeamID, arg.UserID, arg.JoinedAt)
	return err
}

const countOrgMembersByRole = `-- name: CountOrgMembersByRole :one
SELECT COUNT(*)::int AS count FROM org_members WHERE org_id = $1 AND role = $2
`

type CountOrgMembersByRoleParams struct {
	OrgID string
	Role  string
}

func (q *Queries) CountOrgMembersByRole(ctx context.Context, arg CountOrgMembersByRoleParams) (int32, error) {
	row := q.db.QueryRow(ctx, countOrgMembersByRole, arg.OrgID, arg.Role)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const createOrg = `-- name: CreateOrg :exec

INSERT INTO organizations (id, name, slug, personal, owner_id, settings, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateOrgParams struct {
	ID        string
	Name      string
	Slug      string
	Personal  bool
	OwnerID   string
	Settings  json.RawMessage
	CreatedAt time.Time
	UpdatedAt time.Time
}

// Organization queries
func (q *Queries) CreateOrg(ctx context.Context, arg CreateOrgParams) error {
	_, err := q.db.Exec(ctx, createOrg,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Personal,
		arg.OwnerID,
		arg.Settings,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createTeam = `-- name: CreateTeam :exec

INSERT INTO teams (id, org_id, name, description, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateTeamParams struct {
	ID          string
	OrgID       string
	Name        string
	Description *string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

// Team queries
func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) error {
	_, err := q.db.Exec(ctx, createTeam,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.Description,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteTeam = `-- name: DeleteTeam :execresult
DELETE FROM teams WHERE id = $1
`

func (q *Queries) DeleteTeam(ctx context.Context, id string) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteTeam, id)
}

const findOrgByID = `-- name: FindOrgByID :one
SELECT id, name, slug, personal, owner_id, settings, created_at, updated_at
FROM organizations WHERE id = $1
`

func (q *Queries) FindOrgByID(ctx context.Context, id string) (Organization, error) {
	row := q.db.QueryRow(ctx, findOrgByID, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Personal,
		&i.OwnerID,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findOrgBySlug = `-- name: FindOrgBySlug :one
SELECT id, name, slug, personal, owner_id, settings, created_at, updated_at
FROM organizations WHERE slug = $1
`

func (q *Queries) FindOrgBySlug(ctx context.Context, slug string) (Organization, error) {
	row := q.db.QueryRow(ctx, findOrgBySlug, slug)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Personal,
		&i.OwnerID,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findOrgMember = `-- name: FindOrgMember :one
SELECT org_id, user_id, role, joined_at
FROM org_members WHERE org_id = $1 AND user_id = $2
`

type FindOrgMemberParams struct {
	OrgID  string
	UserID string
}

func (q *Queries) FindOrgMember(ctx context.Context, arg FindOrgMemberParams) (OrgMember, error) {
	row := q.db.QueryRow(ctx, findOrgMember, arg.OrgID, arg.UserID)
	var i OrgMember
	err := row.Scan(
		&i.OrgID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const findOrgMembersByOrg = `-- name: FindOrgMembersByOrg :many
SELECT org_id, user_id, role, joined_at
FROM org_members WHERE org_id = $1 ORDER BY joined_at
`

func (q *Queries) FindOrgMembersByOrg(ctx context.Context, orgID string) ([]OrgMember, error) {
	rows, err := q.db.Query(ctx, findOrgMembersByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrgMember{}
	for rows.Next() {
		var i OrgMember
		if err := rows.Scan(
			&i.OrgID,
			&i.UserID,
			&i.Role,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findOrgMembersByUser = `-- name: FindOrgMembersByUser :many
SELECT org_id, user_id, role, joined_at
FROM org_members WHERE user_id = $1 ORDER BY joined_at
`

func (q *Queries) FindOrgMembersByUser(ctx context.Context, userID string) ([]OrgMember, error) {
	rows, err := q.db.Query(ctx, findOrgMembersByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrgMember{}
	for rows.Next() {
		var i OrgMember
		if err := rows.Scan(
			&i.OrgID,
			&i.UserID,
			&i.Role,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findPersonalOrgByOwner = `-- name: FindPersonalOrgByOwner :one
SELECT id, name, slug, personal, owner_id, settings, created_at, updated_at
FROM organizations WHERE owner_id = $1 AND personal = true
`

func (q *Queries) FindPersonalOrgByOwner(ctx context.Context, ownerID string) (Organization, error) {
	row := q.db.QueryRow(ctx, findPersonalOrgByOwner, ownerID)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Personal,
		&i.OwnerID,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findTeamByID = `-- name: FindTeamByID :one
SELECT id, org_id, name, description, created_at, updated_at
FROM teams WHERE id = $1
`

func (q *Queries) FindTeamByID(ctx context.Context, id string) (Team, error) {
	row := q.db.QueryRow(ctx, findTeamByID, id)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findTeamMembers = `-- name: FindTeamMembers :many
SELECT team_id, user_id, joined_at
FROM team_members WHERE team_id = $1 ORDER BY joined_at
`

func (q *Queries) FindTeamMembers(ctx context.Context, teamID string) ([]TeamMember, error) {
	rows, err := q.db.Query(ctx, findTeamMembers, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TeamMember{}
	for rows.Next() {
		var i TeamMember
		if err := rows.Scan(&i.TeamID, &i.UserID, &i.JoinedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findTeamsByOrg = `-- name: FindTeamsByOrg :many
SELECT id, org_id, name, description, created_at, updated_at
FROM teams WHERE org_id = $1 ORDER BY name
`

func (q *Queries) FindTeamsByOrg(ctx context.Context, orgID string) ([]Team, error) {
	rows, err := q.db.Query(ctx, findTeamsByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Team{}
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findTeamsByUser = `-- name: FindTeamsByUser :many
SELECT t.id, t.org_id, t.name, t.description, t.created_at, t.updated_at
FROM teams t JOIN team_members tm ON t.id = tm.team_id
WHERE t.org_id = $1 AND tm.user_id = $2 ORDER BY t.name
`

type FindTeamsByUserParams struct {
	OrgID  string
	UserID string
}

func (q *Queries) FindTeamsByUser(ctx context.Context, arg FindTeamsByUserParams) ([]Team, error) {
	rows, err := q.db.Query(ctx, findTeamsByUser, arg.OrgID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Team{}
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeOrgMember = `-- name: RemoveOrgMember :execresult
DELETE FROM org_members WHERE org_id = $1 AND user_id = $2
`

type RemoveOrgMemberParams struct {
	OrgID  string
	UserID string
}

func (q *Queries) RemoveOrgMember(ctx context.Context, arg RemoveOrgMemberParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, removeOrgMember, arg.OrgID, arg.UserID)
}

const removeTeamMember = `-- name: RemoveTeamMember :execresult
DELETE FROM team_members WHERE team_id = $1 AND user_id = $2
`

type RemoveTeamMemberParams struct {
	TeamID string
	UserID string
}

func (q *Queries) RemoveTeamMember(ctx context.Context, arg RemoveTeamMemberParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, removeTeamMember, arg.TeamID, arg.UserID)
}

const updateOrg = `-- name: UpdateOrg :execresult
UPDATE organizations
SET name = $2, slug = $3, settings = $4, updated_at = $5
WHERE id = $1
`

type UpdateOrgParams struct {
	ID        string
	Name      string
	Slug      string
	Settings  json.RawMessage
	UpdatedAt time.Time
}

func (q *Queries) UpdateOrg(ctx context.Context, arg UpdateOrgParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, updateOrg,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Settings,
		arg.UpdatedAt,
	)
}

const updateOrgMemberRole = `-- name: UpdateOrgMemberRole :execresult
UPDATE org_members SET role = $3 WHERE org_id = $1 AND user_id = $2
`

type UpdateOrgMemberRoleParams struct {
	OrgID  string
	UserID string
	Role   string
}

func (q *Queries) UpdateOrgMemberRole(ctx context.Context, arg UpdateOrgMemberRoleParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, updateOrgMemberRole, arg.OrgID, arg.UserID, arg.Role)
}

const updateTeam = `-- name: UpdateTeam :execresult
UPDATE teams SET name = $2, description = $3, updated_at = $4
WHERE id = $1
`

type UpdateTeamParams struct {
	ID          string
	Name        string
	Description *string
	UpdatedAt   time.Time
}

func (q *Queries) UpdateTeam(ctx context.Context, arg UpdateTeamParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, updateTeam,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.UpdatedAt,
	)
}
