// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
)

type Querier interface {
	// Org member queries
	AddOrgMember(ctx context.Context, arg AddOrgMemberParams) error
	AddTeamMember(ctx context.Context, arg AddTeamMemberParams) error
	CountOrgMembersByRole(ctx context.Context, arg CountOrgMembersByRoleParams) (int32, error)
	// Organization queries
	CreateOrg(ctx context.Context, arg CreateOrgParams) error
	// Team queries
	CreateTeam(ctx context.Context, arg CreateTeamParams) error
	DeleteTeam(ctx context.Context, id string) (pgconn.CommandTag, error)
	FindOrgByID(ctx context.Context, id string) (Organization, error)
	FindOrgBySlug(ctx context.Context, slug string) (Organization, error)
	FindOrgMember(ctx context.Context, arg FindOrgMemberParams) (OrgMember, error)
	FindOrgMembersByOrg(ctx context.Context, orgID string) ([]OrgMember, error)
	FindOrgMembersByUser(ctx context.Context, userID string) ([]OrgMember, error)
	FindPersonalOrgByOwner(ctx context.Context, ownerID string) (Organization, error)
	FindTeamByID(ctx context.Context, id string) (Team, error)
	FindTeamMembers(ctx context.Context, teamID string) ([]TeamMember, error)
	FindTeamsByOrg(ctx context.Context, orgID string) ([]Team, error)
	FindTeamsByUser(ctx context.Context, arg FindTeamsByUserParams) ([]Team, error)
	RemoveOrgMember(ctx context.Context, arg RemoveOrgMemberParams) (pgconn.CommandTag, error)
	RemoveTeamMember(ctx context.Context, arg RemoveTeamMemberParams) (pgconn.CommandTag, error)
	UpdateOrg(ctx context.Context, arg UpdateOrgParams) (pgconn.CommandTag, error)
	UpdateOrgMemberRole(ctx context.Context, arg UpdateOrgMemberRoleParams) (pgconn.CommandTag, error)
	UpdateTeam(ctx context.Context, arg UpdateTeamParams) (pgconn.CommandTag, error)
}

var _ Querier = (*Queries)(nil)
