// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"encoding/json"
	"time"
)

type DomainEntry struct {
	ID           string
	ActorID      string
	Action       string
	ResourceType string
	ResourceID   string
	OrgID        *string
	WorkspaceID  *string
	Metadata     json.RawMessage
	CreatedAt    time.Time
}

type SystemEntry struct {
	ID            string
	EventSubject  string
	EventData     json.RawMessage
	SourceContext string
	CreatedAt     time.Time
}
