// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlc

import (
	"context"
	"encoding/json"
	"time"
)

const appendDomainEntry = `-- name: AppendDomainEntry :exec
INSERT INTO domain_entries (id, actor_id, action, resource_type, resource_id, org_id, workspace_id, metadata, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type AppendDomainEntryParams struct {
	ID           string
	ActorID      string
	Action       string
	ResourceType string
	ResourceID   string
	OrgID        *string
	WorkspaceID  *string
	Metadata     json.RawMessage
	CreatedAt    time.Time
}

func (q *Queries) AppendDomainEntry(ctx context.Context, arg AppendDomainEntryParams) error {
	_, err := q.db.Exec(ctx, appendDomainEntry,
		arg.ID,
		arg.ActorID,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.OrgID,
		arg.WorkspaceID,
		arg.Metadata,
		arg.CreatedAt,
	)
	return err
}

const appendSystemEntry = `-- name: AppendSystemEntry :exec
INSERT INTO system_entries (id, event_subject, event_data, source_context, created_at)
VALUES ($1, $2, $3, $4, $5)
`

type AppendSystemEntryParams struct {
	ID            string
	EventSubject  string
	EventData     json.RawMessage
	SourceContext string
	CreatedAt     time.Time
}

func (q *Queries) AppendSystemEntry(ctx context.Context, arg AppendSystemEntryParams) error {
	_, err := q.db.Exec(ctx, appendSystemEntry,
		arg.ID,
		arg.EventSubject,
		arg.EventData,
		arg.SourceContext,
		arg.CreatedAt,
	)
	return err
}

const findDomainEntries = `-- name: FindDomainEntries :many
SELECT id, actor_id, action, resource_type, resource_id, org_id, workspace_id, metadata, created_at
FROM domain_entries
WHERE ($1::text IS NULL OR actor_id = $1)
  AND ($2::text IS NULL OR action = $2)
  AND ($3::text IS NULL OR resource_type = $3)
  AND ($4::text IS NULL OR resource_id = $4)
  AND ($5::text IS NULL OR org_id = $5)
  AND ($6::text IS NULL OR workspace_id = $6)
  AND ($7::timestamptz IS NULL OR created_at > $7)
  AND ($8::timestamptz IS NULL OR created_at < $8)
ORDER BY created_at DESC
LIMIT $9
`

type FindDomainEntriesParams struct {
	ActorID      *string
	Action       *string
	ResourceType *string
	ResourceID   *string
	OrgID        *string
	WorkspaceID  *string
	After        *time.Time
	Before       *time.Time
	QueryLimit   int
}

func (q *Queries) FindDomainEntries(ctx context.Context, arg FindDomainEntriesParams) ([]DomainEntry, error) {
	rows, err := q.db.Query(ctx, findDomainEntries,
		arg.ActorID,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.OrgID,
		arg.WorkspaceID,
		arg.After,
		arg.Before,
		arg.QueryLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DomainEntry{}
	for rows.Next() {
		var i DomainEntry
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.OrgID,
			&i.WorkspaceID,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findSystemEntries = `-- name: FindSystemEntries :many
SELECT id, event_subject, event_data, source_context, created_at
FROM system_entries
WHERE ($1::text IS NULL OR source_context = $1)
  AND ($2::text IS NULL OR event_subject = $2)
  AND ($3::timestamptz IS NULL OR created_at > $3)
  AND ($4::timestamptz IS NULL OR created_at < $4)
ORDER BY created_at DESC
LIMIT $5
`

type FindSystemEntriesParams struct {
	SourceContext *string
	EventSubject  *string
	After         *time.Time
	Before        *time.Time
	QueryLimit    int
}

func (q *Queries) FindSystemEntries(ctx context.Context, arg FindSystemEntriesParams) ([]SystemEntry, error) {
	rows, err := q.db.Query(ctx, findSystemEntries,
		arg.SourceContext,
		arg.EventSubject,
		arg.After,
		arg.Before,
		arg.QueryLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SystemEntry{}
	for rows.Next() {
		var i SystemEntry
		if err := rows.Scan(
			&i.ID,
			&i.EventSubject,
			&i.EventData,
			&i.SourceContext,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
