// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	AppendDomainEntry(ctx context.Context, arg AppendDomainEntryParams) error
	AppendSystemEntry(ctx context.Context, arg AppendSystemEntryParams) error
	FindDomainEntries(ctx context.Context, arg FindDomainEntriesParams) ([]DomainEntry, error)
	FindSystemEntries(ctx context.Context, arg FindSystemEntriesParams) ([]SystemEntry, error)
}

var _ Querier = (*Queries)(nil)
