// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"
)

type Workflow struct {
	ID            string
	WorkspaceID   string
	InitiatorID   string
	SourceLeafIds []string
	ResultLeafID  *string
	Status        string
	FailureReason *string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}
