// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgconn"
)

const createWorkflow = `-- name: CreateWorkflow :exec
INSERT INTO workflows (id, workspace_id, initiator_id, source_leaf_ids, result_leaf_id,
    status, failure_reason, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateWorkflowParams struct {
	ID            string
	WorkspaceID   string
	InitiatorID   string
	SourceLeafIds []string
	ResultLeafID  *string
	Status        string
	FailureReason *string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) CreateWorkflow(ctx context.Context, arg CreateWorkflowParams) error {
	_, err := q.db.Exec(ctx, createWorkflow,
		arg.ID,
		arg.WorkspaceID,
		arg.InitiatorID,
		arg.SourceLeafIds,
		arg.ResultLeafID,
		arg.Status,
		arg.FailureReason,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const findWorkflowByID = `-- name: FindWorkflowByID :one
SELECT id, workspace_id, initiator_id, source_leaf_ids, result_leaf_id,
    status, failure_reason, created_at, updated_at
FROM workflows WHERE id = $1
`

func (q *Queries) FindWorkflowByID(ctx context.Context, id string) (Workflow, error) {
	row := q.db.QueryRow(ctx, findWorkflowByID, id)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.InitiatorID,
		&i.SourceLeafIds,
		&i.ResultLeafID,
		&i.Status,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findWorkflowsByWorkspace = `-- name: FindWorkflowsByWorkspace :many
SELECT id, workspace_id, initiator_id, source_leaf_ids, result_leaf_id,
    status, failure_reason, created_at, updated_at
FROM workflows WHERE workspace_id = $1 ORDER BY created_at
`

func (q *Queries) FindWorkflowsByWorkspace(ctx context.Context, workspaceID string) ([]Workflow, error) {
	rows, err := q.db.Query(ctx, findWorkflowsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workflow{}
	for rows.Next() {
		var i Workflow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.InitiatorID,
			&i.SourceLeafIds,
			&i.ResultLeafID,
			&i.Status,
			&i.FailureReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorkflow = `-- name: UpdateWorkflow :execresult
UPDATE workflows
SET status = $2, result_leaf_id = $3, failure_reason = $4, updated_at = $5
WHERE id = $1
`

type UpdateWorkflowParams struct {
	ID            string
	Status        string
	ResultLeafID  *string
	FailureReason *string
	UpdatedAt     time.Time
}

func (q *Queries) UpdateWorkflow(ctx context.Context, arg UpdateWorkflowParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, updateWorkflow,
		arg.ID,
		arg.Status,
		arg.ResultLeafID,
		arg.FailureReason,
		arg.UpdatedAt,
	)
}
