// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
)

type Querier interface {
	CreateWorkflow(ctx context.Context, arg CreateWorkflowParams) error
	FindWorkflowByID(ctx context.Context, id string) (Workflow, error)
	FindWorkflowsByWorkspace(ctx context.Context, workspaceID string) ([]Workflow, error)
	UpdateWorkflow(ctx context.Context, arg UpdateWorkflowParams) (pgconn.CommandTag, error)
}

var _ Querier = (*Queries)(nil)
