// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"
)

type Deliverable struct {
	ID            string
	WorkspaceID   string
	Format        string
	Content       string
	SourceLeafIds []string
	Version       int32
	CreatedAt     time.Time
	UpdatedAt     time.Time
	Finalized     bool
}
