// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
)

type Querier interface {
	CreateDeliverable(ctx context.Context, arg CreateDeliverableParams) error
	FindDeliverableByID(ctx context.Context, id string) (Deliverable, error)
	FindDeliverablesByWorkspace(ctx context.Context, workspaceID string) ([]Deliverable, error)
	UpdateDeliverable(ctx context.Context, arg UpdateDeliverableParams) (pgconn.CommandTag, error)
}

var _ Querier = (*Queries)(nil)
