// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgconn"
)

const createDeliverable = `-- name: CreateDeliverable :exec
INSERT INTO deliverables (id, workspace_id, format, content, source_leaf_ids, version, created_at, updated_at, finalized)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateDeliverableParams struct {
	ID            string
	WorkspaceID   string
	Format        string
	Content       string
	SourceLeafIds []string
	Version       int32
	CreatedAt     time.Time
	UpdatedAt     time.Time
	Finalized     bool
}

func (q *Queries) CreateDeliverable(ctx context.Context, arg CreateDeliverableParams) error {
	_, err := q.db.Exec(ctx, createDeliverable,
		arg.ID,
		arg.WorkspaceID,
		arg.Format,
		arg.Content,
		arg.SourceLeafIds,
		arg.Version,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Finalized,
	)
	return err
}

const findDeliverableByID = `-- name: FindDeliverableByID :one
SELECT id, workspace_id, format, content, source_leaf_ids, version, created_at, updated_at, finalized
FROM deliverables WHERE id = $1
`

func (q *Queries) FindDeliverableByID(ctx context.Context, id string) (Deliverable, error) {
	row := q.db.QueryRow(ctx, findDeliverableByID, id)
	var i Deliverable
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Format,
		&i.Content,
		&i.SourceLeafIds,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Finalized,
	)
	return i, err
}

const findDeliverablesByWorkspace = `-- name: FindDeliverablesByWorkspace :many
SELECT id, workspace_id, format, content, source_leaf_ids, version, created_at, updated_at, finalized
FROM deliverables WHERE workspace_id = $1 ORDER BY created_at
`

func (q *Queries) FindDeliverablesByWorkspace(ctx context.Context, workspaceID string) ([]Deliverable, error) {
	rows, err := q.db.Query(ctx, findDeliverablesByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Deliverable{}
	for rows.Next() {
		var i Deliverable
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Format,
			&i.Content,
			&i.SourceLeafIds,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Finalized,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDeliverable = `-- name: UpdateDeliverable :execresult
UPDATE deliverables
SET format = $2, content = $3, source_leaf_ids = $4, version = $5, updated_at = $6, finalized = $7
WHERE id = $1
`

type UpdateDeliverableParams struct {
	ID            string
	Format        string
	Content       string
	SourceLeafIds []string
	Version       int32
	UpdatedAt     time.Time
	Finalized     bool
}

func (q *Queries) UpdateDeliverable(ctx context.Context, arg UpdateDeliverableParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, updateDeliverable,
		arg.ID,
		arg.Format,
		arg.Content,
		arg.SourceLeafIds,
		arg.Version,
		arg.UpdatedAt,
		arg.Finalized,
	)
}
