// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"encoding/json"
	"time"
)

type Checkpoint struct {
	ID          string
	WorkspaceID string
	LeafIds     []string
	Status      string
	Signals     json.RawMessage
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Signal struct {
	ID          string
	WorkspaceID string
	LeafID      string
	UserID      string
	SignalType  string
	Annotation  *string
	CreatedAt   time.Time
}
