// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
)

type Querier interface {
	CountSignalsByLeaf(ctx context.Context, leafID string) ([]CountSignalsByLeafRow, error)
	// Checkpoint queries
	CreateCheckpoint(ctx context.Context, arg CreateCheckpointParams) error
	// Signal queries
	CreateSignal(ctx context.Context, arg CreateSignalParams) error
	DeleteSignal(ctx context.Context, id string) (pgconn.CommandTag, error)
	FindCheckpointByID(ctx context.Context, id string) (Checkpoint, error)
	FindCheckpointsByWorkspace(ctx context.Context, workspaceID string) ([]Checkpoint, error)
	FindOpenCheckpointsByWorkspace(ctx context.Context, workspaceID string) ([]Checkpoint, error)
	FindSignalByLeafAndUser(ctx context.Context, arg FindSignalByLeafAndUserParams) (Signal, error)
	FindSignalsByLeaf(ctx context.Context, leafID string) ([]Signal, error)
	FindSignalsByUser(ctx context.Context, arg FindSignalsByUserParams) ([]Signal, error)
	UpdateCheckpoint(ctx context.Context, arg UpdateCheckpointParams) (pgconn.CommandTag, error)
}

var _ Querier = (*Queries)(nil)
