// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/jackc/pgx/v5/pgconn"
)

const countSignalsByLeaf = `-- name: CountSignalsByLeaf :many
SELECT signal_type, COUNT(*)::int AS count
FROM signals WHERE leaf_id = $1 GROUP BY signal_type
`

type CountSignalsByLeafRow struct {
	SignalType string
	Count      int32
}

func (q *Queries) CountSignalsByLeaf(ctx context.Context, leafID string) ([]CountSignalsByLeafRow, error) {
	rows, err := q.db.Query(ctx, countSignalsByLeaf, leafID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountSignalsByLeafRow{}
	for rows.Next() {
		var i CountSignalsByLeafRow
		if err := rows.Scan(&i.SignalType, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createCheckpoint = `-- name: CreateCheckpoint :exec

INSERT INTO checkpoints (id, workspace_id, leaf_ids, status, signals, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateCheckpointParams struct {
	ID          string
	WorkspaceID string
	LeafIds     []string
	Status      string
	Signals     json.RawMessage
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

// Checkpoint queries
func (q *Queries) CreateCheckpoint(ctx context.Context, arg CreateCheckpointParams) error {
	_, err := q.db.Exec(ctx, createCheckpoint,
		arg.ID,
		arg.WorkspaceID,
		arg.LeafIds,
		arg.Status,
		arg.Signals,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createSignal = `-- name: CreateSignal :exec

INSERT INTO signals (id, workspace_id, leaf_id, user_id, signal_type, annotation, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateSignalParams struct {
	ID          string
	WorkspaceID string
	LeafID      string
	UserID      string
	SignalType  string
	Annotation  *string
	CreatedAt   time.Time
}

// Signal queries
func (q *Queries) CreateSignal(ctx context.Context, arg CreateSignalParams) error {
	_, err := q.db.Exec(ctx, createSignal,
		arg.ID,
		arg.WorkspaceID,
		arg.LeafID,
		arg.UserID,
		arg.SignalType,
		arg.Annotation,
		arg.CreatedAt,
	)
	return err
}

const deleteSignal = `-- name: DeleteSignal :execresult
DELETE FROM signals WHERE id = $1
`

func (q *Queries) DeleteSignal(ctx context.Context, id string) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteSignal, id)
}

const findCheckpointByID = `-- name: FindCheckpointByID :one
SELECT id, workspace_id, leaf_ids, status, signals, created_at, updated_at
FROM checkpoints WHERE id = $1
`

func (q *Queries) FindCheckpointByID(ctx context.Context, id string) (Checkpoint, error) {
	row := q.db.QueryRow(ctx, findCheckpointByID, id)
	var i Checkpoint
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.LeafIds,
		&i.Status,
		&i.Signals,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findCheckpointsByWorkspace = `-- name: FindCheckpointsByWorkspace :many
SELECT id, workspace_id, leaf_ids, status, signals, created_at, updated_at
FROM checkpoints WHERE workspace_id = $1 ORDER BY created_at
`

func (q *Queries) FindCheckpointsByWorkspace(ctx context.Context, workspaceID string) ([]Checkpoint, error) {
	rows, err := q.db.Query(ctx, findCheckpointsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Checkpoint{}
	for rows.Next() {
		var i Checkpoint
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.LeafIds,
			&i.Status,
			&i.Signals,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findOpenCheckpointsByWorkspace = `-- name: FindOpenCheckpointsByWorkspace :many
SELECT id, workspace_id, leaf_ids, status, signals, created_at, updated_at
FROM checkpoints WHERE workspace_id = $1 AND status = 'open' ORDER BY created_at
`

func (q *Queries) FindOpenCheckpointsByWorkspace(ctx context.Context, workspaceID string) ([]Checkpoint, error) {
	rows, err := q.db.Query(ctx, findOpenCheckpointsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Checkpoint{}
	for rows.Next() {
		var i Checkpoint
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.LeafIds,
			&i.Status,
			&i.Signals,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findSignalByLeafAndUser = `-- name: FindSignalByLeafAndUser :one
SELECT id, workspace_id, leaf_id, user_id, signal_type, annotation, created_at
FROM signals WHERE leaf_id = $1 AND user_id = $2
`

type FindSignalByLeafAndUserParams struct {
	LeafID string
	UserID string
}

func (q *Queries) FindSignalByLeafAndUser(ctx context.Context, arg FindSignalByLeafAndUserParams) (Signal, error) {
	row := q.db.QueryRow(ctx, findSignalByLeafAndUser, arg.LeafID, arg.UserID)
	var i Signal
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.LeafID,
		&i.UserID,
		&i.SignalType,
		&i.Annotation,
		&i.CreatedAt,
	)
	return i, err
}

const findSignalsByLeaf = `-- name: FindSignalsByLeaf :many
SELECT id, workspace_id, leaf_id, user_id, signal_type, annotation, created_at
FROM signals WHERE leaf_id = $1 ORDER BY created_at
`

func (q *Queries) FindSignalsByLeaf(ctx context.Context, leafID string) ([]Signal, error) {
	rows, err := q.db.Query(ctx, findSignalsByLeaf, leafID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Signal{}
	for rows.Next() {
		var i Signal
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.LeafID,
			&i.UserID,
			&i.SignalType,
			&i.Annotation,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findSignalsByUser = `-- name: FindSignalsByUser :many
SELECT id, workspace_id, leaf_id, user_id, signal_type, annotation, created_at
FROM signals WHERE workspace_id = $1 AND user_id = $2 ORDER BY created_at
`

type FindSignalsByUserParams struct {
	WorkspaceID string
	UserID      string
}

func (q *Queries) FindSignalsByUser(ctx context.Context, arg FindSignalsByUserParams) ([]Signal, error) {
	rows, err := q.db.Query(ctx, findSignalsByUser, arg.WorkspaceID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Signal{}
	for rows.Next() {
		var i Signal
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.LeafID,
			&i.UserID,
			&i.SignalType,
			&i.Annotation,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCheckpoint = `-- name: UpdateCheckpoint :execresult
UPDATE checkpoints SET status = $2, signals = $3, updated_at = $4
WHERE id = $1
`

type UpdateCheckpointParams struct {
	ID        string
	Status    string
	Signals   json.RawMessage
	UpdatedAt time.Time
}

func (q *Queries) UpdateCheckpoint(ctx context.Context, arg UpdateCheckpointParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, updateCheckpoint,
		arg.ID,
		arg.Status,
		arg.Signals,
		arg.UpdatedAt,
	)
}
