// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	FindThreadByLeaf(ctx context.Context, leafID string) (Thread, error)
	SaveThread(ctx context.Context, arg SaveThreadParams) error
	ThreadExists(ctx context.Context, leafID string) (bool, error)
}

var _ Querier = (*Queries)(nil)
