// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlc

import (
	"context"
	"encoding/json"
)

const findThreadByLeaf = `-- name: FindThreadByLeaf :one
SELECT leaf_id, comments FROM threads WHERE leaf_id = $1
`

func (q *Queries) FindThreadByLeaf(ctx context.Context, leafID string) (Thread, error) {
	row := q.db.QueryRow(ctx, findThreadByLeaf, leafID)
	var i Thread
	err := row.Scan(&i.LeafID, &i.Comments)
	return i, err
}

const saveThread = `-- name: SaveThread :exec
INSERT INTO threads (leaf_id, comments)
VALUES ($1, $2)
ON CONFLICT (leaf_id) DO UPDATE SET comments = $2
`

type SaveThreadParams struct {
	LeafID   string
	Comments json.RawMessage
}

func (q *Queries) SaveThread(ctx context.Context, arg SaveThreadParams) error {
	_, err := q.db.Exec(ctx, saveThread, arg.LeafID, arg.Comments)
	return err
}

const threadExists = `-- name: ThreadExists :one
SELECT EXISTS(SELECT 1 FROM threads WHERE leaf_id = $1) AS exists
`

func (q *Queries) ThreadExists(ctx context.Context, leafID string) (bool, error) {
	row := q.db.QueryRow(ctx, threadExists, leafID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
