// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"encoding/json"
	"time"
)

type Session struct {
	ID           string
	WorkspaceID  string
	UserID       string
	SeedID       string
	ParentLeafID *string
	SessionType  string
	Status       string
	Messages     json.RawMessage
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
