// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/jackc/pgx/v5/pgconn"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (id, workspace_id, user_id, seed_id, parent_leaf_id,
    session_type, status, messages, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type CreateSessionParams struct {
	ID           string
	WorkspaceID  string
	UserID       string
	SeedID       string
	ParentLeafID *string
	SessionType  string
	Status       string
	Messages     json.RawMessage
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession,
		arg.ID,
		arg.WorkspaceID,
		arg.UserID,
		arg.SeedID,
		arg.ParentLeafID,
		arg.SessionType,
		arg.Status,
		arg.Messages,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const findActiveSessionsByUser = `-- name: FindActiveSessionsByUser :many
SELECT id, workspace_id, user_id, seed_id, parent_leaf_id,
    session_type, status, messages, created_at, updated_at
FROM sessions
WHERE workspace_id = $1 AND user_id = $2 AND status NOT IN ('completed', 'abandoned')
ORDER BY created_at DESC
`

type FindActiveSessionsByUserParams struct {
	WorkspaceID string
	UserID      string
}

func (q *Queries) FindActiveSessionsByUser(ctx context.Context, arg FindActiveSessionsByUserParams) ([]Session, error) {
	rows, err := q.db.Query(ctx, findActiveSessionsByUser, arg.WorkspaceID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.UserID,
			&i.SeedID,
			&i.ParentLeafID,
			&i.SessionType,
			&i.Status,
			&i.Messages,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findSessionByID = `-- name: FindSessionByID :one
SELECT id, workspace_id, user_id, seed_id, parent_leaf_id,
    session_type, status, messages, created_at, updated_at
FROM sessions WHERE id = $1
`

func (q *Queries) FindSessionByID(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRow(ctx, findSessionByID, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.SeedID,
		&i.ParentLeafID,
		&i.SessionType,
		&i.Status,
		&i.Messages,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSession = `-- name: UpdateSession :execresult
UPDATE sessions
SET status = $2, messages = $3, updated_at = $4
WHERE id = $1
`

type UpdateSessionParams struct {
	ID        string
	Status    string
	Messages  json.RawMessage
	UpdatedAt time.Time
}

func (q *Queries) UpdateSession(ctx context.Context, arg UpdateSessionParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, updateSession,
		arg.ID,
		arg.Status,
		arg.Messages,
		arg.UpdatedAt,
	)
}
