// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
)

type Querier interface {
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	FindActiveSessionsByUser(ctx context.Context, arg FindActiveSessionsByUserParams) ([]Session, error)
	FindSessionByID(ctx context.Context, id string) (Session, error)
	FindSessionsByWorkspace(ctx context.Context, workspaceID string) ([]Session, error)
	UpdateSession(ctx context.Context, arg UpdateSessionParams) (pgconn.CommandTag, error)
}

var _ Querier = (*Queries)(nil)
