// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"
)

type Notification struct {
	ID           string
	UserID       string
	Channel      string
	Title        string
	Body         *string
	ResourceType *string
	ResourceID   *string
	WorkspaceID  *string
	Status       string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type Subscription struct {
	UserID          string
	WorkspaceID     string
	Channels        []string
	DigestFrequency string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}
