// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
)

type Querier interface {
	CreateNotification(ctx context.Context, arg CreateNotificationParams) error
	FindNotificationsByUser(ctx context.Context, arg FindNotificationsByUserParams) ([]Notification, error)
	FindSubscriptionByUserAndWorkspace(ctx context.Context, arg FindSubscriptionByUserAndWorkspaceParams) (Subscription, error)
	FindSubscriptionsByWorkspace(ctx context.Context, workspaceID string) ([]Subscription, error)
	FindUnreadNotificationsByUser(ctx context.Context, userID string) ([]Notification, error)
	MarkAllNotificationsRead(ctx context.Context, userID string) error
	SaveSubscription(ctx context.Context, arg SaveSubscriptionParams) error
	UpdateNotification(ctx context.Context, arg UpdateNotificationParams) (pgconn.CommandTag, error)
}

var _ Querier = (*Queries)(nil)
