// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgconn"
)

const createNotification = `-- name: CreateNotification :exec
INSERT INTO notifications (id, user_id, channel, title, body, resource_type, resource_id, workspace_id, status, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type CreateNotificationParams struct {
	ID           string
	UserID       string
	Channel      string
	Title        string
	Body         *string
	ResourceType *string
	ResourceID   *string
	WorkspaceID  *string
	Status       string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) error {
	_, err := q.db.Exec(ctx, createNotification,
		arg.ID,
		arg.UserID,
		arg.Channel,
		arg.Title,
		arg.Body,
		arg.ResourceType,
		arg.ResourceID,
		arg.WorkspaceID,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const findNotificationByID = `-- name: FindNotificationByID :one
SELECT id, user_id, channel, title, body, resource_type, resource_id, workspace_id, status, created_at, updated_at
FROM notifications WHERE id = $1
`

func (q *Queries) FindNotificationByID(ctx context.Context, id string) (Notification, error) {
	row := q.db.QueryRow(ctx, findNotificationByID, id)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Channel,
		&i.Title,
		&i.Body,
		&i.ResourceType,
		&i.ResourceID,
		&i.WorkspaceID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findNotificationsByUser = `-- name: FindNotificationsByUser :many
SELECT id, user_id, channel, title, body, resource_type, resource_id, workspace_id, status, created_at, updated_at
FROM notifications WHERE user_id = $1
ORDER BY created_at DESC LIMIT $2
`

type FindNotificationsByUserParams struct {
	UserID string
	Limit  int
}

func (q *Queries) FindNotificationsByUser(ctx context.Context, arg FindNotificationsByUserParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, findNotificationsByUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Channel,
			&i.Title,
			&i.Body,
			&i.ResourceType,
			&i.ResourceID,
			&i.WorkspaceID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findSubscriptionByUserAndWorkspace = `-- name: FindSubscriptionByUserAndWorkspace :one
SELECT user_id, workspace_id, channels, digest_frequency, created_at, updated_at
FROM subscriptions WHERE user_id = $1 AND workspace_id = $2
`

type FindSubscriptionByUserAndWorkspaceParams struct {
	UserID      string
	WorkspaceID string
}

func (q *Queries) FindSubscriptionByUserAndWorkspace(ctx context.Context, arg FindSubscriptionByUserAndWorkspaceParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, findSubscriptionByUserAndWorkspace, arg.UserID, arg.WorkspaceID)
	var i Subscription
	err := row.Scan(
		&i.UserID,
		&i.WorkspaceID,
		&i.Channels,
		&i.DigestFrequency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findSubscriptionsByWorkspace = `-- name: FindSubscriptionsByWorkspace :many
SELECT user_id, workspace_id, channels, digest_frequency, created_at, updated_at
FROM subscriptions WHERE workspace_id = $1
`

func (q *Queries) FindSubscriptionsByWorkspace(ctx context.Context, workspaceID string) ([]Subscription, error) {
	rows, err := q.db.Query(ctx, findSubscriptionsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subscription{}
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.UserID,
			&i.WorkspaceID,
			&i.Channels,
			&i.DigestFrequency,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findUnreadNotificationsByUser = `-- name: FindUnreadNotificationsByUser :many
SELECT id, user_id, channel, title, body, resource_type, resource_id, workspace_id, status, created_at, updated_at
FROM notifications WHERE user_id = $1 AND status != 'read'
ORDER BY created_at DESC
`

func (q *Queries) FindUnreadNotificationsByUser(ctx context.Context, userID string) ([]Notification, error) {
	rows, err := q.db.Query(ctx, findUnreadNotificationsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Channel,
			&i.Title,
			&i.Body,
			&i.ResourceType,
			&i.ResourceID,
			&i.WorkspaceID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :exec
UPDATE notifications SET status = 'read', updated_at = NOW()
WHERE user_id = $1 AND status != 'read'
`

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, markAllNotificationsRead, userID)
	return err
}

const saveSubscription = `-- name: SaveSubscription :exec
INSERT INTO subscriptions (user_id, workspace_id, channels, digest_frequency, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (user_id, workspace_id) DO UPDATE
SET channels = $3, digest_frequency = $4, updated_at = $6
`

type SaveSubscriptionParams struct {
	UserID          string
	WorkspaceID     string
	Channels        []string
	DigestFrequency string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

func (q *Queries) SaveSubscription(ctx context.Context, arg SaveSubscriptionParams) error {
	_, err := q.db.Exec(ctx, saveSubscription,
		arg.UserID,
		arg.WorkspaceID,
		arg.Channels,
		arg.DigestFrequency,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const updateNotification = `-- name: UpdateNotification :execresult
UPDATE notifications SET status = $2, updated_at = $3 WHERE id = $1
`

type UpdateNotificationParams struct {
	ID        string
	Status    string
	UpdatedAt time.Time
}

func (q *Queries) UpdateNotification(ctx context.Context, arg UpdateNotificationParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, updateNotification, arg.ID, arg.Status, arg.UpdatedAt)
}
