// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"encoding/json"
	"time"
)

type Branch struct {
	ID          string
	WorkspaceID string
	SeedID      string
	AuthorID    string
	RootLeafID  *string
	CreatedAt   time.Time
}

type Connection struct {
	ID          string
	WorkspaceID string
	AuthorID    string
	LeafIds     []string
	CreatedAt   time.Time
}

type Leafe struct {
	ID            string
	WorkspaceID   string
	SeedID        string
	BranchID      string
	AuthorID      string
	ParentLeafID  *string
	Title         string
	Summary       string
	KeyPoints     []string
	OpenQuestions []string
	Tags          []string
	Layer         string
	Sources       json.RawMessage
	Metadata      json.RawMessage
	CreatedAt     time.Time
}
