// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
)

type Querier interface {
	// Branch queries
	CreateBranch(ctx context.Context, arg CreateBranchParams) error
	// Connection queries
	CreateConnection(ctx context.Context, arg CreateConnectionParams) error
	// Leaf queries
	CreateLeaf(ctx context.Context, arg CreateLeafParams) error
	FindBranchByID(ctx context.Context, id string) (Branch, error)
	FindBranchesByAuthor(ctx context.Context, arg FindBranchesByAuthorParams) ([]Branch, error)
	FindBranchesBySeed(ctx context.Context, seedID string) ([]Branch, error)
	FindBranchesByWorkspace(ctx context.Context, workspaceID string) ([]Branch, error)
	FindConnectionByID(ctx context.Context, id string) (Connection, error)
	FindConnectionsByLeaf(ctx context.Context, leafID string) ([]Connection, error)
	FindConnectionsByWorkspace(ctx context.Context, workspaceID string) ([]Connection, error)
	FindLeafByID(ctx context.Context, id string) (Leafe, error)
	FindLeavesByBranch(ctx context.Context, branchID string) ([]Leafe, error)
	FindLeavesByIDs(ctx context.Context, dollar_1 []string) ([]Leafe, error)
	FindLeavesBySeed(ctx context.Context, seedID string) ([]Leafe, error)
	FindLeavesByWorkspace(ctx context.Context, arg FindLeavesByWorkspaceParams) ([]Leafe, error)
	UpdateBranch(ctx context.Context, arg UpdateBranchParams) (pgconn.CommandTag, error)
	UpdateLeafLayer(ctx context.Context, arg UpdateLeafLayerParams) (pgconn.CommandTag, error)
	UpdateLeafPosition(ctx context.Context, arg UpdateLeafPositionParams) (pgconn.CommandTag, error)
}

var _ Querier = (*Queries)(nil)
