// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/jackc/pgx/v5/pgconn"
)

const createBranch = `-- name: CreateBranch :exec

INSERT INTO branches (id, workspace_id, seed_id, author_id, root_leaf_id, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateBranchParams struct {
	ID          string
	WorkspaceID string
	SeedID      string
	AuthorID    string
	RootLeafID  *string
	CreatedAt   time.Time
}

// Branch queries
func (q *Queries) CreateBranch(ctx context.Context, arg CreateBranchParams) error {
	_, err := q.db.Exec(ctx, createBranch,
		arg.ID,
		arg.WorkspaceID,
		arg.SeedID,
		arg.AuthorID,
		arg.RootLeafID,
		arg.CreatedAt,
	)
	return err
}

const createConnection = `-- name: CreateConnection :exec

INSERT INTO connections (id, workspace_id, author_id, leaf_ids, created_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateConnectionParams struct {
	ID          string
	WorkspaceID string
	AuthorID    string
	LeafIds     []string
	CreatedAt   time.Time
}

// Connection queries
func (q *Queries) CreateConnection(ctx context.Context, arg CreateConnectionParams) error {
	_, err := q.db.Exec(ctx, createConnection,
		arg.ID,
		arg.WorkspaceID,
		arg.AuthorID,
		arg.LeafIds,
		arg.CreatedAt,
	)
	return err
}

const createLeaf = `-- name: CreateLeaf :exec

INSERT INTO leaves (id, workspace_id, seed_id, branch_id, author_id, parent_leaf_id,
    title, summary, key_points, open_questions, tags, layer, sources, metadata, created_at, position_x, position_y)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17)
`

type CreateLeafParams struct {
	ID            string
	WorkspaceID   string
	SeedID        string
	BranchID      string
	AuthorID      string
	ParentLeafID  *string
	Title         string
	Summary       string
	KeyPoints     []string
	OpenQuestions []string
	Tags          []string
	Layer         string
	Sources       json.RawMessage
	Metadata      json.RawMessage
	CreatedAt     time.Time
	PositionX     float64
	PositionY     float64
}

// Leaf queries
func (q *Queries) CreateLeaf(ctx context.Context, arg CreateLeafParams) error {
	_, err := q.db.Exec(ctx, createLeaf,
		arg.ID,
		arg.WorkspaceID,
		arg.SeedID,
		arg.BranchID,
		arg.AuthorID,
		arg.ParentLeafID,
		arg.Title,
		arg.Summary,
		arg.KeyPoints,
		arg.OpenQuestions,
		arg.Tags,
		arg.Layer,
		arg.Sources,
		arg.Metadata,
		arg.CreatedAt,
		arg.PositionX,
		arg.PositionY,
	)
	return err
}

const findBranchByID = `-- name: FindBranchByID :one
SELECT id, workspace_id, seed_id, author_id, root_leaf_id, created_at
FROM branches WHERE id = $1
`

func (q *Queries) FindBranchByID(ctx context.Context, id string) (Branch, error) {
	row := q.db.QueryRow(ctx, findBranchByID, id)
	var i Branch
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.SeedID,
		&i.AuthorID,
		&i.RootLeafID,
		&i.CreatedAt,
	)
	return i, err
}

const findBranchesByAuthor = `-- name: FindBranchesByAuthor :many
SELECT id, workspace_id, seed_id, author_id, root_leaf_id, created_at
FROM branches WHERE workspace_id = $1 AND author_id = $2 ORDER BY created_at
`

type FindBranchesByAuthorParams struct {
	WorkspaceID string
	AuthorID    string
}

func (q *Queries) FindBranchesByAuthor(ctx context.Context, arg FindBranchesByAuthorParams) ([]Branch, error) {
	rows, err := q.db.Query(ctx, findBranchesByAuthor, arg.WorkspaceID, arg.AuthorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Branch{}
	for rows.Next() {
		var i Branch
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.SeedID,
			&i.AuthorID,
			&i.RootLeafID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findBranchesBySeed = `-- name: FindBranchesBySeed :many
SELECT id, workspace_id, seed_id, author_id, root_leaf_id, created_at
FROM branches WHERE seed_id = $1 ORDER BY created_at
`

func (q *Queries) FindBranchesBySeed(ctx context.Context, seedID string) ([]Branch, error) {
	rows, err := q.db.Query(ctx, findBranchesBySeed, seedID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Branch{}
	for rows.Next() {
		var i Branch
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.SeedID,
			&i.AuthorID,
			&i.RootLeafID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findBranchesByWorkspace = `-- name: FindBranchesByWorkspace :many
SELECT id, workspace_id, seed_id, author_id, root_leaf_id, created_at
FROM branches WHERE workspace_id = $1 ORDER BY created_at
`

func (q *Queries) FindBranchesByWorkspace(ctx context.Context, workspaceID string) ([]Branch, error) {
	rows, err := q.db.Query(ctx, findBranchesByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Branch{}
	for rows.Next() {
		var i Branch
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.SeedID,
			&i.AuthorID,
			&i.RootLeafID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findConnectionByID = `-- name: FindConnectionByID :one
SELECT id, workspace_id, author_id, leaf_ids, created_at
FROM connections WHERE id = $1
`

func (q *Queries) FindConnectionByID(ctx context.Context, id string) (Connection, error) {
	row := q.db.QueryRow(ctx, findConnectionByID, id)
	var i Connection
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.AuthorID,
		&i.LeafIds,
		&i.CreatedAt,
	)
	return i, err
}

const findConnectionsByLeaf = `-- name: FindConnectionsByLeaf :many
SELECT id, workspace_id, author_id, leaf_ids, created_at
FROM connections WHERE $1::text = ANY(leaf_ids) ORDER BY created_at
`

func (q *Queries) FindConnectionsByLeaf(ctx context.Context, leafID string) ([]Connection, error) {
	rows, err := q.db.Query(ctx, findConnectionsByLeaf, leafID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Connection{}
	for rows.Next() {
		var i Connection
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.AuthorID,
			&i.LeafIds,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findConnectionsByWorkspace = `-- name: FindConnectionsByWorkspace :many
SELECT id, workspace_id, author_id, leaf_ids, created_at
FROM connections WHERE workspace_id = $1 ORDER BY created_at
`

func (q *Queries) FindConnectionsByWorkspace(ctx context.Context, workspaceID string) ([]Connection, error) {
	rows, err := q.db.Query(ctx, findConnectionsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Connection{}
	for rows.Next() {
		var i Connection
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.AuthorID,
			&i.LeafIds,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findLeafByID = `-- name: FindLeafByID :one
SELECT id, workspace_id, seed_id, branch_id, author_id, parent_leaf_id,
    title, summary, key_points, open_questions, tags, layer, sources, metadata, created_at, position_x, position_y
FROM leaves WHERE id = $1
`

func (q *Queries) FindLeafByID(ctx context.Context, id string) (Leafe, error) {
	row := q.db.QueryRow(ctx, findLeafByID, id)
	var i Leafe
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.SeedID,
		&i.BranchID,
		&i.AuthorID,
		&i.ParentLeafID,
		&i.Title,
		&i.Summary,
		&i.KeyPoints,
		&i.OpenQuestions,
		&i.Tags,
		&i.Layer,
		&i.Sources,
		&i.Metadata,
		&i.CreatedAt,
		&i.PositionX,
		&i.PositionY,
	)
	return i, err
}

const findLeavesByBranch = `-- name: FindLeavesByBranch :many
SELECT id, workspace_id, seed_id, branch_id, author_id, parent_leaf_id,
    title, summary, key_points, open_questions, tags, layer, sources, metadata, created_at, position_x, position_y
FROM leaves WHERE branch_id = $1 ORDER BY created_at
`

func (q *Queries) FindLeavesByBranch(ctx context.Context, branchID string) ([]Leafe, error) {
	rows, err := q.db.Query(ctx, findLeavesByBranch, branchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Leafe{}
	for rows.Next() {
		var i Leafe
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.SeedID,
			&i.BranchID,
			&i.AuthorID,
			&i.ParentLeafID,
			&i.Title,
			&i.Summary,
			&i.KeyPoints,
			&i.OpenQuestions,
			&i.Tags,
			&i.Layer,
			&i.Sources,
			&i.Metadata,
			&i.CreatedAt,
			&i.PositionX,
			&i.PositionY,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findLeavesByIDs = `-- name: FindLeavesByIDs :many
SELECT id, workspace_id, seed_id, branch_id, author_id, parent_leaf_id,
    title, summary, key_points, open_questions, tags, layer, sources, metadata, created_at, position_x, position_y
FROM leaves WHERE id = ANY($1::text[])
`

func (q *Queries) FindLeavesByIDs(ctx context.Context, dollar_1 []string) ([]Leafe, error) {
	rows, err := q.db.Query(ctx, findLeavesByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Leafe{}
	for rows.Next() {
		var i Leafe
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.SeedID,
			&i.BranchID,
			&i.AuthorID,
			&i.ParentLeafID,
			&i.Title,
			&i.Summary,
			&i.KeyPoints,
			&i.OpenQuestions,
			&i.Tags,
			&i.Layer,
			&i.Sources,
			&i.Metadata,
			&i.CreatedAt,
			&i.PositionX,
			&i.PositionY,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findLeavesBySeed = `-- name: FindLeavesBySeed :many
SELECT id, workspace_id, seed_id, branch_id, author_id, parent_leaf_id,
    title, summary, key_points, open_questions, tags, layer, sources, metadata, created_at, position_x, position_y
FROM leaves WHERE seed_id = $1 ORDER BY created_at
`

func (q *Queries) FindLeavesBySeed(ctx context.Context, seedID string) ([]Leafe, error) {
	rows, err := q.db.Query(ctx, findLeavesBySeed, seedID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Leafe{}
	for rows.Next() {
		var i Leafe
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.SeedID,
			&i.BranchID,
			&i.AuthorID,
			&i.ParentLeafID,
			&i.Title,
			&i.Summary,
			&i.KeyPoints,
			&i.OpenQuestions,
			&i.Tags,
			&i.Layer,
			&i.Sources,
			&i.Metadata,
			&i.CreatedAt,
			&i.PositionX,
			&i.PositionY,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findLeavesByWorkspace = `-- name: FindLeavesByWorkspace :many
SELECT id, workspace_id, seed_id, branch_id, author_id, parent_leaf_id,
    title, summary, key_points, open_questions, tags, layer, sources, metadata, created_at, position_x, position_y
FROM leaves
WHERE workspace_id = $1
  AND ($2::text IS NULL OR author_id = $2)
  AND ($3::text IS NULL OR seed_id = $3)
  AND ($4::text IS NULL OR layer = $4)
  AND ($5::text[] IS NULL OR tags && $5)
ORDER BY created_at
`

type FindLeavesByWorkspaceParams struct {
	WorkspaceID string
	AuthorID    *string
	SeedID      *string
	Layer       *string
	Tags        []string
}

func (q *Queries) FindLeavesByWorkspace(ctx context.Context, arg FindLeavesByWorkspaceParams) ([]Leafe, error) {
	rows, err := q.db.Query(ctx, findLeavesByWorkspace,
		arg.WorkspaceID,
		arg.AuthorID,
		arg.SeedID,
		arg.Layer,
		arg.Tags,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Leafe{}
	for rows.Next() {
		var i Leafe
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.SeedID,
			&i.BranchID,
			&i.AuthorID,
			&i.ParentLeafID,
			&i.Title,
			&i.Summary,
			&i.KeyPoints,
			&i.OpenQuestions,
			&i.Tags,
			&i.Layer,
			&i.Sources,
			&i.Metadata,
			&i.CreatedAt,
			&i.PositionX,
			&i.PositionY,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBranch = `-- name: UpdateBranch :execresult
UPDATE branches SET root_leaf_id = $2 WHERE id = $1
`

type UpdateBranchParams struct {
	ID         string
	RootLeafID *string
}

func (q *Queries) UpdateBranch(ctx context.Context, arg UpdateBranchParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, updateBranch, arg.ID, arg.RootLeafID)
}

const updateLeafLayer = `-- name: UpdateLeafLayer :execresult
UPDATE leaves SET layer = $2 WHERE id = $1
`

type UpdateLeafLayerParams struct {
	ID    string
	Layer string
}

func (q *Queries) UpdateLeafLayer(ctx context.Context, arg UpdateLeafLayerParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, updateLeafLayer, arg.ID, arg.Layer)
}

const updateLeafPosition = `-- name: UpdateLeafPosition :execresult
UPDATE leaves SET position_x = $2, position_y = $3 WHERE id = $1
`

type UpdateLeafPositionParams struct {
	ID        string
	PositionX float64
	PositionY float64
}

func (q *Queries) UpdateLeafPosition(ctx context.Context, arg UpdateLeafPositionParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, updateLeafPosition, arg.ID, arg.PositionX, arg.PositionY)
}
