// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"encoding/json"
	"time"
)

type Seed struct {
	ID          string
	WorkspaceID string
	AuthorID    string
	Title       string
	Description *string
	Constraints json.RawMessage
	Tags        []string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	PositionX   float64
	PositionY   float64
}
