// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
)

type Querier interface {
	CreateSeed(ctx context.Context, arg CreateSeedParams) error
	FindSeedByID(ctx context.Context, id string) (Seed, error)
	FindSeedsByWorkspace(ctx context.Context, workspaceID string) ([]Seed, error)
	UpdateSeed(ctx context.Context, arg UpdateSeedParams) (pgconn.CommandTag, error)
	UpdateSeedPosition(ctx context.Context, arg UpdateSeedPositionParams) (pgconn.CommandTag, error)
}

var _ Querier = (*Queries)(nil)
