// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/jackc/pgx/v5/pgconn"
)

const createSeed = `-- name: CreateSeed :exec
INSERT INTO seeds (id, workspace_id, author_id, title, description, constraints, tags, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateSeedParams struct {
	ID          string
	WorkspaceID string
	AuthorID    string
	Title       string
	Description *string
	Constraints json.RawMessage
	Tags        []string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) CreateSeed(ctx context.Context, arg CreateSeedParams) error {
	_, err := q.db.Exec(ctx, createSeed,
		arg.ID,
		arg.WorkspaceID,
		arg.AuthorID,
		arg.Title,
		arg.Description,
		arg.Constraints,
		arg.Tags,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const findSeedByID = `-- name: FindSeedByID :one
SELECT id, workspace_id, author_id, title, description, constraints, tags, created_at, updated_at
FROM seeds WHERE id = $1
`

func (q *Queries) FindSeedByID(ctx context.Context, id string) (Seed, error) {
	row := q.db.QueryRow(ctx, findSeedByID, id)
	var i Seed
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.AuthorID,
		&i.Title,
		&i.Description,
		&i.Constraints,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findSeedsByWorkspace = `-- name: FindSeedsByWorkspace :many
SELECT id, workspace_id, author_id, title, description, constraints, tags, created_at, updated_at
FROM seeds WHERE workspace_id = $1 ORDER BY created_at
`

func (q *Queries) FindSeedsByWorkspace(ctx context.Context, workspaceID string) ([]Seed, error) {
	rows, err := q.db.Query(ctx, findSeedsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Seed{}
	for rows.Next() {
		var i Seed
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.AuthorID,
			&i.Title,
			&i.Description,
			&i.Constraints,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSeed = `-- name: UpdateSeed :execresult
UPDATE seeds
SET constraints = $2, tags = $3, updated_at = $4
WHERE id = $1
`

type UpdateSeedParams struct {
	ID          string
	Constraints json.RawMessage
	Tags        []string
	UpdatedAt   time.Time
}

func (q *Queries) UpdateSeed(ctx context.Context, arg UpdateSeedParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, updateSeed,
		arg.ID,
		arg.Constraints,
		arg.Tags,
		arg.UpdatedAt,
	)
}
