// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"encoding/json"
	"time"
)

type Workspace struct {
	ID             string
	OrgID          string
	TeamID         *string
	Name           string
	Description    *string
	Phase          string
	LoreKeeperMode string
	LoreKeeperID   *string
	Configuration  json.RawMessage
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type WorkspaceMember struct {
	WorkspaceID string
	UserID      string
	Role        string
	JoinedAt    time.Time
}
