// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/jackc/pgx/v5/pgconn"
)

const addWorkspaceMember = `-- name: AddWorkspaceMember :exec

INSERT INTO workspace_members (workspace_id, user_id, role, joined_at)
VALUES ($1, $2, $3, $4)
`

type AddWorkspaceMemberParams struct {
	WorkspaceID string
	UserID      string
	Role        string
	JoinedAt    time.Time
}

// Workspace member queries
func (q *Queries) AddWorkspaceMember(ctx context.Context, arg AddWorkspaceMemberParams) error {
	_, err := q.db.Exec(ctx, addWorkspaceMember,
		arg.WorkspaceID,
		arg.UserID,
		arg.Role,
		arg.JoinedAt,
	)
	return err
}

const createWorkspace = `-- name: CreateWorkspace :exec

INSERT INTO workspaces (id, org_id, team_id, name, description, phase, lore_keeper_mode, lore_keeper_id, configuration, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type CreateWorkspaceParams struct {
	ID             string
	OrgID          string
	TeamID         *string
	Name           string
	Description    *string
	Phase          string
	LoreKeeperMode string
	LoreKeeperID   *string
	Configuration  json.RawMessage
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

// Workspace queries
func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) error {
	_, err := q.db.Exec(ctx, createWorkspace,
		arg.ID,
		arg.OrgID,
		arg.TeamID,
		arg.Name,
		arg.Description,
		arg.Phase,
		arg.LoreKeeperMode,
		arg.LoreKeeperID,
		arg.Configuration,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteLLMConfig = `-- name: DeleteLLMConfig :execresult
DELETE FROM llm_configs WHERE workspace_id = $1
`

func (q *Queries) DeleteLLMConfig(ctx context.Context, workspaceID string) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteLLMConfig, workspaceID)
}

const findLLMConfigByWorkspace = `-- name: FindLLMConfigByWorkspace :one
SELECT workspace_id, provider, model, api_key_enc, created_at, updated_at
FROM llm_configs WHERE workspace_id = $1
`

func (q *Queries) FindLLMConfigByWorkspace(ctx context.Context, workspaceID string) (LlmConfig, error) {
	row := q.db.QueryRow(ctx, findLLMConfigByWorkspace, workspaceID)
	var i LlmConfig
	err := row.Scan(
		&i.WorkspaceID,
		&i.Provider,
		&i.Model,
		&i.ApiKeyEnc,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findWorkspaceByID = `-- name: FindWorkspaceByID :one
SELECT id, org_id, team_id, name, description, phase, lore_keeper_mode, lore_keeper_id, configuration, created_at, updated_at
FROM workspaces WHERE id = $1
`

func (q *Queries) FindWorkspaceByID(ctx context.Context, id string) (Workspace, error) {
	row := q.db.QueryRow(ctx, findWorkspaceByID, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.TeamID,
		&i.Name,
		&i.Description,
		&i.Phase,
		&i.LoreKeeperMode,
		&i.LoreKeeperID,
		&i.Configuration,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findWorkspaceMember = `-- name: FindWorkspaceMember :one
SELECT workspace_id, user_id, role, joined_at
FROM workspace_members WHERE workspace_id = $1 AND user_id = $2
`

type FindWorkspaceMemberParams struct {
	WorkspaceID string
	UserID      string
}

func (q *Queries) FindWorkspaceMember(ctx context.Context, arg FindWorkspaceMemberParams) (WorkspaceMember, error) {
	row := q.db.QueryRow(ctx, findWorkspaceMember, arg.WorkspaceID, arg.UserID)
	var i WorkspaceMember
	err := row.Scan(
		&i.WorkspaceID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const findWorkspaceMembersByUser = `-- name: FindWorkspaceMembersByUser :many
SELECT wm.workspace_id, wm.user_id, wm.role, wm.joined_at
FROM workspace_members wm
JOIN workspaces w ON w.id = wm.workspace_id
WHERE w.org_id = $1 AND wm.user_id = $2
ORDER BY wm.joined_at
`

type FindWorkspaceMembersByUserParams struct {
	OrgID  string
	UserID string
}

func (q *Queries) FindWorkspaceMembersByUser(ctx context.Context, arg FindWorkspaceMembersByUserParams) ([]WorkspaceMember, error) {
	rows, err := q.db.Query(ctx, findWorkspaceMembersByUser, arg.OrgID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkspaceMember{}
	for rows.Next() {
		var i WorkspaceMember
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.UserID,
			&i.Role,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findWorkspaceMembersByWorkspace = `-- name: FindWorkspaceMembersByWorkspace :many
SELECT workspace_id, user_id, role, joined_at
FROM workspace_members WHERE workspace_id = $1 ORDER BY joined_at
`

func (q *Queries) FindWorkspaceMembersByWorkspace(ctx context.Context, workspaceID string) ([]WorkspaceMember, error) {
	rows, err := q.db.Query(ctx, findWorkspaceMembersByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkspaceMember{}
	for rows.Next() {
		var i WorkspaceMember
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.UserID,
			&i.Role,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findWorkspacesByOrg = `-- name: FindWorkspacesByOrg :many
SELECT id, org_id, team_id, name, description, phase, lore_keeper_mode, lore_keeper_id, configuration, created_at, updated_at
FROM workspaces WHERE org_id = $1 ORDER BY created_at
`

func (q *Queries) FindWorkspacesByOrg(ctx context.Context, orgID string) ([]Workspace, error) {
	rows, err := q.db.Query(ctx, findWorkspacesByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workspace{}
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.TeamID,
			&i.Name,
			&i.Description,
			&i.Phase,
			&i.LoreKeeperMode,
			&i.LoreKeeperID,
			&i.Configuration,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findWorkspacesByTeam = `-- name: FindWorkspacesByTeam :many
SELECT id, org_id, team_id, name, description, phase, lore_keeper_mode, lore_keeper_id, configuration, created_at, updated_at
FROM workspaces WHERE team_id = $1 ORDER BY created_at
`

func (q *Queries) FindWorkspacesByTeam(ctx context.Context, teamID *string) ([]Workspace, error) {
	rows, err := q.db.Query(ctx, findWorkspacesByTeam, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workspace{}
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.TeamID,
			&i.Name,
			&i.Description,
			&i.Phase,
			&i.LoreKeeperMode,
			&i.LoreKeeperID,
			&i.Configuration,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeWorkspaceMember = `-- name: RemoveWorkspaceMember :execresult
DELETE FROM workspace_members WHERE workspace_id = $1 AND user_id = $2
`

type RemoveWorkspaceMemberParams struct {
	WorkspaceID string
	UserID      string
}

func (q *Queries) RemoveWorkspaceMember(ctx context.Context, arg RemoveWorkspaceMemberParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, removeWorkspaceMember, arg.WorkspaceID, arg.UserID)
}

const updateWorkspace = `-- name: UpdateWorkspace :execresult
UPDATE workspaces
SET name = $2, description = $3, phase = $4, lore_keeper_mode = $5,
    lore_keeper_id = $6, configuration = $7, updated_at = $8
WHERE id = $1
`

type UpdateWorkspaceParams struct {
	ID             string
	Name           string
	Description    *string
	Phase          string
	LoreKeeperMode string
	LoreKeeperID   *string
	Configuration  json.RawMessage
	UpdatedAt      time.Time
}

func (q *Queries) UpdateWorkspace(ctx context.Context, arg UpdateWorkspaceParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, updateWorkspace,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Phase,
		arg.LoreKeeperMode,
		arg.LoreKeeperID,
		arg.Configuration,
		arg.UpdatedAt,
	)
}

const updateWorkspaceMemberRole = `-- name: UpdateWorkspaceMemberRole :execresult
UPDATE workspace_members SET role = $3 WHERE workspace_id = $1 AND user_id = $2
`

type UpdateWorkspaceMemberRoleParams struct {
	WorkspaceID string
	UserID      string
	Role        string
}

func (q *Queries) UpdateWorkspaceMemberRole(ctx context.Context, arg UpdateWorkspaceMemberRoleParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, updateWorkspaceMemberRole, arg.WorkspaceID, arg.UserID, arg.Role)
}

const upsertLLMConfig = `-- name: UpsertLLMConfig :exec

INSERT INTO llm_configs (workspace_id, provider, model, api_key_enc, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (workspace_id)
DO UPDATE SET provider = EXCLUDED.provider, model = EXCLUDED.model,
             api_key_enc = EXCLUDED.api_key_enc, updated_at = EXCLUDED.updated_at
`

type UpsertLLMConfigParams struct {
	WorkspaceID string
	Provider    string
	Model       string
	ApiKeyEnc   []byte
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

// LLM config queries
func (q *Queries) UpsertLLMConfig(ctx context.Context, arg UpsertLLMConfigParams) error {
	_, err := q.db.Exec(ctx, upsertLLMConfig,
		arg.WorkspaceID,
		arg.Provider,
		arg.Model,
		arg.ApiKeyEnc,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
