// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
)

type Querier interface {
	// Workspace member queries
	AddWorkspaceMember(ctx context.Context, arg AddWorkspaceMemberParams) error
	// Workspace queries
	CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) error
	FindWorkspaceByID(ctx context.Context, id string) (Workspace, error)
	FindWorkspaceMember(ctx context.Context, arg FindWorkspaceMemberParams) (WorkspaceMember, error)
	FindWorkspaceMembersByUser(ctx context.Context, arg FindWorkspaceMembersByUserParams) ([]WorkspaceMember, error)
	FindWorkspaceMembersByWorkspace(ctx context.Context, workspaceID string) ([]WorkspaceMember, error)
	FindWorkspacesByOrg(ctx context.Context, orgID string) ([]Workspace, error)
	FindWorkspacesByTeam(ctx context.Context, teamID *string) ([]Workspace, error)
	RemoveWorkspaceMember(ctx context.Context, arg RemoveWorkspaceMemberParams) (pgconn.CommandTag, error)
	UpdateWorkspace(ctx context.Context, arg UpdateWorkspaceParams) (pgconn.CommandTag, error)
	UpdateWorkspaceMemberRole(ctx context.Context, arg UpdateWorkspaceMemberRoleParams) (pgconn.CommandTag, error)
}

var _ Querier = (*Queries)(nil)
