// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"
)

type User struct {
	ID          string
	ExternalID  string
	DisplayName string
	Email       string
	AvatarUrl   *string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
