// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgconn"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users (id, external_id, display_name, email, avatar_url, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateUserParams struct {
	ID          string
	ExternalID  string
	DisplayName string
	Email       string
	AvatarUrl   *string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.ID,
		arg.ExternalID,
		arg.DisplayName,
		arg.Email,
		arg.AvatarUrl,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteUserLLMConfig = `-- name: DeleteUserLLMConfig :execresult
DELETE FROM user_llm_configs WHERE user_id = $1
`

func (q *Queries) DeleteUserLLMConfig(ctx context.Context, userID string) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteUserLLMConfig, userID)
}

const findUserByExternalID = `-- name: FindUserByExternalID :one
SELECT id, external_id, display_name, email, avatar_url, created_at, updated_at
FROM users WHERE external_id = $1
`

func (q *Queries) FindUserByExternalID(ctx context.Context, externalID string) (User, error) {
	row := q.db.QueryRow(ctx, findUserByExternalID, externalID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.DisplayName,
		&i.Email,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findUserByID = `-- name: FindUserByID :one
SELECT id, external_id, display_name, email, avatar_url, created_at, updated_at
FROM users WHERE id = $1
`

func (q *Queries) FindUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, findUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.DisplayName,
		&i.Email,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findUserLLMConfigByUser = `-- name: FindUserLLMConfigByUser :one
SELECT user_id, provider, model, api_key_enc, created_at, updated_at
FROM user_llm_configs WHERE user_id = $1
`

func (q *Queries) FindUserLLMConfigByUser(ctx context.Context, userID string) (UserLlmConfig, error) {
	row := q.db.QueryRow(ctx, findUserLLMConfigByUser, userID)
	var i UserLlmConfig
	err := row.Scan(
		&i.UserID,
		&i.Provider,
		&i.Model,
		&i.ApiKeyEnc,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findUsersByIDs = `-- name: FindUsersByIDs :many
SELECT id, external_id, display_name, email, avatar_url, created_at, updated_at
FROM users WHERE id = ANY($1::text[])
`

func (q *Queries) FindUsersByIDs(ctx context.Context, dollar_1 []string) ([]User, error) {
	rows, err := q.db.Query(ctx, findUsersByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.DisplayName,
			&i.Email,
			&i.AvatarUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :execresult
UPDATE users
SET display_name = $2, email = $3, avatar_url = $4, updated_at = $5
WHERE id = $1
`

type UpdateUserParams struct {
	ID          string
	DisplayName string
	Email       string
	AvatarUrl   *string
	UpdatedAt   time.Time
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, updateUser,
		arg.ID,
		arg.DisplayName,
		arg.Email,
		arg.AvatarUrl,
		arg.UpdatedAt,
	)
}

const upsertUserLLMConfig = `-- name: UpsertUserLLMConfig :exec
INSERT INTO user_llm_configs (user_id, provider, model, api_key_enc, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (user_id) DO UPDATE
SET provider = EXCLUDED.provider, model = EXCLUDED.model,
    api_key_enc = EXCLUDED.api_key_enc, updated_at = EXCLUDED.updated_at
`

type UpsertUserLLMConfigParams struct {
	UserID    string
	Provider  string
	Model     string
	ApiKeyEnc []byte
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) UpsertUserLLMConfig(ctx context.Context, arg UpsertUserLLMConfigParams) error {
	_, err := q.db.Exec(ctx, upsertUserLLMConfig,
		arg.UserID,
		arg.Provider,
		arg.Model,
		arg.ApiKeyEnc,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
